name: star_movie_idf
description: Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  presentation:
    path: packages/presentation
  data:
    path: packages/data

  cupertino_icons: ^1.0.2
  firebase_core: ^1.24.0
  firebase_crashlytics: ^2.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - prod.json
    - sandbox.json

flutter_intl:
  enabled: true