name: build_pr
on:
  pull_request:
    branches:
      - master
jobs:
  pull_request_build:
    name: Build after PR
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.0.5'
          channel: 'stable'
      - name: Create api key for android
        run: |
          touch "local.properties";
          echo "${{secrets.FACEBOOK_APP_ID}}" >> local.properties;
          echo "${{secrets.FB_LOGIN_PROTOCOL_SCHEME}}" >> local.properties;
          echo "${{secrets.FACEBOOK_CLIENT_TOKEN}}" >> local.properties;
        working-directory: android/
      - name: Create api key
        run: |
          mkdir environmentСonfiguration
          touch "environmentСonfiguration/sandbox.json";
          echo "${{secrets.SANDBOX_API_KEY}}" >> sandbox.json;
        working-directory:
      - name: Pub get domain
        run: |
          flutter pub get && flutter packages pub run build_runner build
        working-directory: packages/domain/
      - name: Pub get data
        run: |
          flutter pub get
        working-directory: packages/data/
      - name: Pub get presentation
        run: |
          flutter pub global activate intl_utils 2.7.0
          flutter pub get
          flutter pub global run intl_utils:generate
        working-directory: packages/presentation/
      - name: Pub get app
        run: |
          flutter pub get
      - name: Build APK
        run: flutter build apk --flavor sandbox -t lib/main_sandbox.dart --debug --dart-define=sandbox=true
      - name: Firebase app distribution push
        uses: wzieba/Firebase-Distribution-Github-Action@v1.4.0
        with:
          appId: ${{secrets.FIREBASE_APP_ID}}
          token: ${{secrets.FIREBASE_TOKEN}}
          groups: testers
          file: build/app/outputs/flutter-apk/app-sandbox-debug.apk