name: build_master
on:
  push:
    branches:
      - master
jobs:
  after_master_commit:
    name: Build after master commit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.0.5'
          channel: 'stable'
      - name: Create api key for android
        run: |
          touch "local.properties";
          echo "${{secrets.FACEBOOK_APP_ID}}" >> local.properties;
          echo "${{secrets.FB_LOGIN_PROTOCOL_SCHEME}}" >> local.properties;
          echo "${{secrets.FACEBOOK_CLIENT_TOKEN}}" >> local.properties;
        working-directory: android/
      - name: Create api key
        run: |
          mkdir environmentСonfiguration
          touch "environmentСonfiguration/prod.json";
          echo "${{secrets.PROD_API_KEY}}" >> prod.json;
      - name: Pub get domain
        run: |
          flutter pub get && flutter packages pub run build_runner build
        working-directory: packages/domain/
      - name: Pub get data
        run: |
          flutter pub get
        working-directory: packages/data/
      - name: Pub get presentation
        run: |
          flutter pub global activate intl_utils 2.7.0
          flutter pub get
          flutter pub global run intl_utils:generate
        working-directory: packages/presentation/
      - name: Pub get app
        run: |
          flutter pub get
      - name: Build APK
        run: flutter build apk --flavor prod -t lib/main_prod.dart --release --dart-define=prod=true
      - name: Github release push
        uses: ncipollo/release-action@v1.11.1
        with:
          artifacts: build/app/outputs/flutter-apk/app-prod-release.apk
          tag: Release
          token: ${{ secrets.GITHUB_TOKEN }}