
name: build_pr

on:
  pull_request:
    branches:
      - master

jobs:
  pull_request_build:
    name: Build after PR
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '3.3.4'
          channel: 'stable'
      - name: Build APK
        run: flutter build apk --flavor sandbox --dart-define=sandbox=true -t lib/main_sandbox.dart --debug
